# Generated by Django 6.0.3 on 2026-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('opening_balance', models.FloatField(blank=True, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=60)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('phone2', models.CharField(blank=True, default='', max_length=60)),
                ('openingdepartment', models.CharField(blank=True, default='', max_length=30)),
                ('area', models.CharField(blank=True, default='', max_length=30)),
                ('super_code', models.CharField(default='DEBTO', max_length=5)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('gstin', models.CharField(blank=True, default='', max_length=30)),
                ('remarkcolumntitle', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'acc_master',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'acc_departments',
                'ordering': ['department_id'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('departments_ok', models.IntegerField(default=0)),
                ('departments_fail', models.IntegerField(default=0)),
                ('debtors_ok', models.IntegerField(default=0)),
                ('debtors_fail', models.IntegerField(default=0)),
                ('mode', models.CharField(default='push', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
