# Generated by Django 5.2.15 on 2026-06-18 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('sub_category', models.CharField(blank=True, default='', max_length=60)),
                ('department', models.CharField(blank=True, default='', max_length=30)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('sale_rate', models.FloatField(blank=True, null=True)),
                ('purchase_rate', models.FloatField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('opening_qty', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'acc_product',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='synclog',
            name='productbatches_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='productbatches_ok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='products_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='products_ok',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(blank=True, default='', max_length=60)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('purchase_rate', models.FloatField(blank=True, null=True)),
                ('sale_rate', models.FloatField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=60)),
                ('product', models.ForeignKey(db_column='product_code', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.product')),
            ],
            options={
                'db_table': 'acc_productbatch',
                'ordering': ['product_id', 'batch_no'],
            },
        ),
    ]
