# Generated by Django 5.2.15 on 2026-06-19 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_synclog_productbatches_fail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(db_column='product_code', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.product'),
        ),
    ]
