# Generated by Django 5.2.15 on 2026-06-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productbatch_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbatch',
            options={'ordering': ['product_id', 'barcode']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='department',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='productbatch',
            old_name='mrp',
            new_name='bmrp',
        ),
        migrations.RenameField(
            model_name='productbatch',
            old_name='purchase_rate',
            new_name='fourthprice',
        ),
        migrations.RenameField(
            model_name='productbatch',
            old_name='qty',
            new_name='nlc1',
        ),
        migrations.RenameField(
            model_name='productbatch',
            old_name='sale_rate',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='opening_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='mfg_date',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='nameinsl',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='taxcode',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='text6',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='salesprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='secondprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='thirdprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
