# Generated by Django 5.2.15 on 2026-06-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productbatch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbatch',
            options={'ordering': ['product_id']},
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='batch_id',
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='product',
            field=models.OneToOneField(db_column='product_code', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='batch', serialize=False, to='api.product'),
        ),
    ]
